<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.7 setup script
 * Date: Tue, 26 Feb 2013 10:07:02 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: mysql.xunem.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql.xunem.com';
$cfg['Servers'][$i]['host'] = 'mysql.xunem.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '512ccee11e8ca8.32752619';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>